<a href="https://colab.research.google.com/github/Vu529/P.h.D-AI-project/blob/main/Stp1_VEE_CODE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install chembl_webresource_client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.8-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 1.9 MB/s
Collecting requests-cache~=0.7.0
  Downloading requests_cache-0.7.5-py3-none-any.whl (39 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (1.24.3)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (2.23.0)
Requirement already satisfied: easydict in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (1.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2022.5.18.1)
Collecting url-normalize<2.0,>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Collecting itsdangerous>=2.0.1
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Requirement already satisfied: attrs<22.0,>=21.2 in /usr/local/lib/python3.7/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (21.4.0)
Collecting pyyaml>=5.4
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 10.6 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from url-normalize<2.0,>=1.4->requests-cache~=0.7.0->chembl_webresource_client) (1.15.0)
Installing collected packages: url-normalize, pyyaml, itsdangerous, requests-cache, chembl-webresource-client
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: itsdangerous
    Found existing installation: itsdangerous 1.1.0
    Uninstalling itsdangerous-1.1.0:
      Successfully uninstalled itsdangerous-1.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires itsdangerous<2.0,>=0.24, but you have itsdangerous 2.1.2 which is incompatible.
Successfully installed chembl-webresource-client-0.10.8 itsdangerous-2.1.2 pyyaml-6.0 requests-cache-0.7.5 url-normalize-1.4.3

In [2]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Search for target protein

In [3]:
target= new_client.target
target_query= target.search("neddylation activation enzyme")
targets= pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,DCN1-like protein 1/NEDD8-conjugating enzyme U...,16.0,False,CHEMBL4523603,"[{'accession': 'Q96GG9', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
1,"[{'xref_id': 'Q70AG6', 'xref_name': None, 'xre...",Rattus norvegicus,Cytidine deaminase,13.0,False,CHEMBL3653,"[{'accession': 'Q70AG6', 'component_descriptio...",SINGLE PROTEIN,10116.0
2,"[{'xref_id': 'Q12884', 'xref_name': None, 'xre...",Homo sapiens,Fibroblast activation protein alpha,13.0,False,CHEMBL4683,"[{'accession': 'Q12884', 'component_descriptio...",SINGLE PROTEIN,9606.0
3,"[{'xref_id': 'P97321', 'xref_name': None, 'xre...",Mus musculus,Seprase,13.0,False,CHEMBL5769,"[{'accession': 'P97321', 'component_descriptio...",SINGLE PROTEIN,10090.0
4,[],Homo sapiens,Early activation antigen CD69,13.0,False,CHEMBL3308911,"[{'accession': 'Q07108', 'component_descriptio...",SINGLE PROTEIN,9606.0
...,...,...,...,...,...,...,...,...,...
756,[],Homo sapiens,NLR family CARD domain-containing protein 4,1.0,False,CHEMBL4630857,"[{'accession': 'Q9NPP4', 'component_descriptio...",SINGLE PROTEIN,9606.0
757,[],Homo sapiens,Na(+)/H(+) exchange regulatory cofactor NHE-RF2,1.0,False,CHEMBL4739686,"[{'accession': 'Q15599', 'component_descriptio...",SINGLE PROTEIN,9606.0
758,[],Rattus norvegicus,Adenylate cyclase,0.0,False,CHEMBL2095179,"[{'accession': 'D4A3N4', 'component_descriptio...",PROTEIN FAMILY,10116.0
759,[],Homo sapiens,Voltage-gated calcium channel,0.0,False,CHEMBL2363032,"[{'accession': 'O95180', 'component_descriptio...",PROTEIN COMPLEX GROUP,9606.0
760,[],Homo sapiens,Cyclin-dependent kinase,0.0,False,CHEMBL3559691,"[{'accession': 'P06493', 'component_descriptio...",PROTEIN FAMILY,9606.0

# Select and retrieve bioactivity data for Nedd8 Activating Enzyme

In [4]:
selected_target= targets.target_chembl_id[30]
selected_target

'CHEMBL3831283'

# Retrive only Bioactivity data

In [5]:
activity= new_client.activity
res= activity.filter(target_chembl_id=selected_target).filter(standard_type='IC50')

In [6]:
df= pd.DataFrame.from_dict(res)
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,16875836,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
1,None,16875837,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
2,None,16875838,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
3,None,16875839,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
4,None,16875840,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,None,19494115,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.015
286,None,19494116,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.01
287,None,19494117,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.0006
288,None,19494118,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.013
289,None,19494119,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.112

In [7]:
df.standard_type.unique()

array(['IC50'], dtype=object)

# Save the bioactivity data into csv file

In [8]:
df.to_csv('NAE_bioactivity_data.csv', index=False)

# Handling missing data

In [9]:
df2 = df[df.standard_value.notna()]
df2

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,16875836,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
1,None,16875837,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
2,None,16875838,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
3,None,16875839,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
4,None,16875840,[],CHEMBL3880354,Inhibition of recombinant human NAEalpha/N-ter...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,nM,UO_0000065,None,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,None,19494115,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.015
286,None,19494116,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.01
287,None,19494117,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.0006
288,None,19494118,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.013
289,None,19494119,[],CHEMBL4482792,Inhibition of NAE (unknown origin) using GST-t...,B,None,None,BAO_0000190,BAO_0000223,...,Homo sapiens,NEDD8 activating enzyme,9606,None,None,IC50,uM,UO_0000065,None,0.112

# Iterate the molecule_chembl_id to a list

In [10]:
mol_cid= []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

# Iterate canonical_smiles to a list

In [11]:
canonical_smiles= []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

# Iterate standard value

In [12]:
standard_value= []
for i in df2.standard_value:
  standard_value.append(i)

In [13]:
data_tuples= list(zip(mol_cid, canonical_smiles, standard_value))
df3= pd.DataFrame(data_tuples, columns=['molecule_chembl_id', 'canonical_smiles', 'standard_value'])
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL3910873,CN(c1ncnc2[nH]c(-c3cccc4ccccc34)nc12)[C@H]1C[C...,500.0
1,CHEMBL3958456,Cc1nc(N[C@H]2CCc3ccccc32)nc(N[C@@H]2C[C@H](COS...,500.0
2,CHEMBL3948689,C[C@H]1Cc2ccccc2[C@H]1Nc1cc(O[C@H]2C[C@H](O)[C...,500.0
3,CHEMBL3946042,NS(=O)(=O)OC[C@@H]1C[C@@H](Oc2cc(NCc3cccc4cccc...,500.0
4,CHEMBL3903981,NS(=O)(=O)OC[C@@H]1C[C@@H](Nc2ncnc3[nH]c(-c4cc...,500.0
...,...,...,...
285,CHEMBL4558498,Cc1cc(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)...,15.0
286,CHEMBL4573232,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,10.0
287,CHEMBL4569826,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,0.6
288,CHEMBL4580824,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,13.0
289,CHEMBL4546722,Cc1c(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)(...,112.0

In [14]:
df3_nr = df3.drop_duplicates(['canonical_smiles'])
df3_nr

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL3910873,CN(c1ncnc2[nH]c(-c3cccc4ccccc34)nc12)[C@H]1C[C...,500.0
1,CHEMBL3958456,Cc1nc(N[C@H]2CCc3ccccc32)nc(N[C@@H]2C[C@H](COS...,500.0
2,CHEMBL3948689,C[C@H]1Cc2ccccc2[C@H]1Nc1cc(O[C@H]2C[C@H](O)[C...,500.0
3,CHEMBL3946042,NS(=O)(=O)OC[C@@H]1C[C@@H](Oc2cc(NCc3cccc4cccc...,500.0
4,CHEMBL3903981,NS(=O)(=O)OC[C@@H]1C[C@@H](Nc2ncnc3[nH]c(-c4cc...,500.0
...,...,...,...
285,CHEMBL4558498,Cc1cc(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)...,15.0
286,CHEMBL4573232,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,10.0
287,CHEMBL4569826,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,0.6
288,CHEMBL4580824,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,13.0
289,CHEMBL4546722,Cc1c(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)(...,112.0

# Save dataframe to CSV file

In [15]:
df3.to_csv('NAE_bioactivity01_data.csv', index=False)

# Data pre-processing of bioactivity

# Labeling compounds as either being active, inactive or intermediate
# The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be active while those greater than 10,000 nM will be considered to be inactive. As for those values in between 1,000 and 10,000 nM will be referred to as intermediate.

In [16]:
df4 = pd.read_csv('NAE_bioactivity01_data.csv')

In [17]:
bioactivity_class= []
for  i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
      bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

In [18]:
bioactivity_clas = pd.Series(bioactivity_class, name='class')
df5 = pd.concat([df4, bioactivity_clas], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL3910873,CN(c1ncnc2[nH]c(-c3cccc4ccccc34)nc12)[C@H]1C[C...,500.0,active
1,CHEMBL3958456,Cc1nc(N[C@H]2CCc3ccccc32)nc(N[C@@H]2C[C@H](COS...,500.0,active
2,CHEMBL3948689,C[C@H]1Cc2ccccc2[C@H]1Nc1cc(O[C@H]2C[C@H](O)[C...,500.0,active
3,CHEMBL3946042,NS(=O)(=O)OC[C@@H]1C[C@@H](Oc2cc(NCc3cccc4cccc...,500.0,active
4,CHEMBL3903981,NS(=O)(=O)OC[C@@H]1C[C@@H](Nc2ncnc3[nH]c(-c4cc...,500.0,active
...,...,...,...,...
285,CHEMBL4558498,Cc1cc(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)...,15.0,active
286,CHEMBL4573232,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,10.0,active
287,CHEMBL4569826,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,0.6,active
288,CHEMBL4580824,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,13.0,active
289,CHEMBL4546722,Cc1c(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)(...,112.0,active

# Save dataframe into CSV

In [19]:
df5.to_csv('NAE_bioactivity02_data.csv', index=False)

# Install conda and rdkit for preparing Lipinski molecular descriptors

In [53]:
!conda install -c rdkit rdkit -y

Collecting package metadata (current_repodata.json): - \ | / - \ | / - \ | / - done
Solving environment: | / - \ | / - \ | / - \ | / done

# All requested packages already installed.

In [77]:
sol = pd.read_csv('NAE_bioactivity02_data.csv')

In [78]:
sol1 = sol[sol.canonical_smiles.notna()]

In [80]:
sol1.canonical_smiles

0      CN(c1ncnc2[nH]c(-c3cccc4ccccc34)nc12)[C@H]1C[C...
1      Cc1nc(N[C@H]2CCc3ccccc32)nc(N[C@@H]2C[C@H](COS...
2      C[C@H]1Cc2ccccc2[C@H]1Nc1cc(O[C@H]2C[C@H](O)[C...
3      NS(=O)(=O)OC[C@@H]1C[C@@H](Oc2cc(NCc3cccc4cccc...
4      NS(=O)(=O)OC[C@@H]1C[C@@H](Nc2ncnc3[nH]c(-c4cc...
                             ...
285    Cc1cc(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)...
286    NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...
287    NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...
288    NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...
289    Cc1c(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)(...
Name: canonical_smiles, Length: 289, dtype: object

In [81]:
import numpy as np
from rdkit.Chem import Descriptors
from rdkit import Chem

In [82]:
def generate(smiles, verbose=False):

    moldata= []
    for smiles in sol1.canonical_smiles:
        mol =  Chem.MolFromSmiles(smiles) 
        moldata.append(mol)
      
    baseData= np.arange(1,1)
    i=0  
    for mol in moldata:        
       
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_MolWt = Descriptors.MolWt(mol)
        desc_NumRotatableBonds = Descriptors.NumRotatableBonds(mol)
           
        row = np.array([desc_MolLogP,
                        desc_MolWt,
                        desc_NumRotatableBonds])   
    
        if(i==0):
            baseData=row
        else:
            baseData=np.vstack([baseData, row])
        i=i+1      
    
    columnNames=["MolLogP","MolWt","NumRotatableBonds"]   
    descriptors = pd.DataFrame(data=baseData,columns=columnNames)
    
    return descriptors

In [84]:
df = generate(sol1.canonical_smiles)
df

     MolLogP    MolWt  NumRotatableBonds
0    1.96890  468.539                6.0
1    0.02172  450.521                7.0
2    1.56040  434.518                7.0
3    1.98030  444.513                8.0
4    0.56260  462.488                6.0
..       ...      ...                ...
284  2.03952  587.605                9.0
285  4.24940  681.637               10.0
286  2.48210  521.599                9.0
287  1.42860  640.694               10.0
288  2.91922  637.612                9.0

[289 rows x 3 columns]

In [45]:
df6 = pd.read_csv('NAE_bioactivity02_data.csv')
df6

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL3910873,CN(c1ncnc2[nH]c(-c3cccc4ccccc34)nc12)[C@H]1C[C...,500.0,active
1,CHEMBL3958456,Cc1nc(N[C@H]2CCc3ccccc32)nc(N[C@@H]2C[C@H](COS...,500.0,active
2,CHEMBL3948689,C[C@H]1Cc2ccccc2[C@H]1Nc1cc(O[C@H]2C[C@H](O)[C...,500.0,active
3,CHEMBL3946042,NS(=O)(=O)OC[C@@H]1C[C@@H](Oc2cc(NCc3cccc4cccc...,500.0,active
4,CHEMBL3903981,NS(=O)(=O)OC[C@@H]1C[C@@H](Nc2ncnc3[nH]c(-c4cc...,500.0,active
...,...,...,...,...
285,CHEMBL4558498,Cc1cc(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)...,15.0,active
286,CHEMBL4573232,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,10.0,active
287,CHEMBL4569826,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,0.6,active
288,CHEMBL4580824,NS(=O)(=O)OC[C@H]1C[C@@H](Nc2ncncc2C(=O)c2cn(C...,13.0,active
289,CHEMBL4546722,Cc1c(Cn2cc(C(=O)c3cncnc3N[C@@H]3C[C@H](COS(N)(...,112.0,active

# PadelPy installation

In [ ]:
! pip install padelpy

# Prepare fingerprint xml files

# Download fingerprint xml files

In [ ]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip fingerprints_xml.zip

# List and sort fingerprint xml files

In [ ]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

In [ ]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

In [ ]:
FP_list = ['AtomPairs2DCount',
           'AtomPairs2D',
           'EState',
           'CDKextended',
           'CDK',
           'CDKgraphonly',
           'KlekotaRothCount',
           'KlekotaRoth',
           'MACC',
           'Pubchem',
           'SubstructureCount',
           'Substructure']

Create dictionary

In [ ]:
fp = dict(zip(FP_list, xml_files))
fp

In [ ]:
df5= pd.read_csv('NAE_bioactivity02_data.csv')
df5

In [ ]:
selection = ['canonical_smiles','molecule_chembl_id']
df5_selection = df5[selection]
df5_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
! cat molecule.smi | head -5

In [ ]:
! cat molecule.smi | wc -l

In [ ]:
fp ['Substructure']

In [ ]:
fp ['CDK']

In [ ]:
from padelpy import padeldescriptor
fingerprint = 'CDK'
fingerprint_output_file = ''.join([fingerprint, '.csv']) #'Substructure.csv'
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                  d_file=fingerprint_output_file,#'Substructure.csv'
                  #descriptortypes='SubstructureFingerprint.xml'),
                  descriptortypes= fingerprint_descriptortypes,
                  detectaromaticity=True,
                  standardizenitro=True,
                  standardizetautomers=True,
                  threads=2,
                  removesalt=True,
                  log=True,
                  fingerprints=True)

In [ ]:
Descriptors= pd.read_csv(fingerprint_output_file)
Descriptors

In [ ]:
df_ic=df5['standard_value']
df_ic

In [ ]:
df_combined = pd.concat([Descriptors, df_ic], axis=1)
df_combined

In [ ]:
df_x = df_combined.drop(columns=['Name'])
df_x

# To allow IC50 data to be more uniformly distributed, we will convert IC50 to the negative logarithmic scale which is essentially -log10(IC50).

# This custom function pIC50() will accept a DataFrame as input and will:

# Take the IC50 values from the standard_value column and converts it from nM to M by multiplying the value by 10
# Take the molar value and apply -log10
# Delete the standard_value column and create a new pIC50 column

In [ ]:
# https://github.com/chaninlab/estrogen-receptor-alpha-qsar/blob/master/02_ER_alpha_RO5.ipynb

import numpy as np

def pIC50(input):
    pIC50 = []

    for i in input['standard_value_norm']:
        molar = i*(10**-9) # Converts nM to M
        pIC50.append(-np.log10(molar))

    input['pIC50'] = pIC50
    x = input.drop('standard_value_norm', 1)
        
    return x

# Point to note: Values greater than 100,000,000 will be fixed at 100,000,000 otherwise the negative logarithmic value will become negative.

In [ ]:
df_x.standard_value.describe()

In [ ]:
-np.log10( (10**-9)* 100000000 )

In [ ]:
-np.log10( (10**-9)* 10000000000 )

In [ ]:
def norm_value(input):
    norm = []

    for i in input['standard_value']:
        if i > 100000000:
          i = 100000000
        norm.append(i)

    input['standard_value_norm'] = norm
    x = input.drop('standard_value', 1)
        
    return x

# We will first apply the norm_value() function so that the values in the standard_value column is normalized.

In [ ]:
df_norm = norm_value(df_x)
df_norm

In [ ]:
df_norm.standard_value_norm.describe()

In [ ]:
df_final = pIC50(df_norm)
df_final

In [ ]:
df_final.pIC50.describe()

In [ ]:
df_final.to_csv('PhDCDK_project.csv', index=False)

In [ ]:
ls -l

# Copying files to Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

# Create a data folder in colab notebook folder on Google drive

In [ ]:
! mkdir '/content/gdrive/My Drive/Colab Notebooks/dataCDK'

In [ ]:
! cp PhDCDK_project.csv '/content/gdrive/My Drive/Colab Notebooks/dataCDK'

In [ ]:
! ls -l '/content/gdrive/My Drive/Colab Notebooks/datapCDK'

# View the csv file

In [ ]:
! ls

In [ ]:
! head PhD_project.csv

In [ ]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [ ]:
Dat = pd.read_csv('PhD_project.csv')

In [ ]:
X = Dat.drop('pIC50', axis=1)
X